# -*- coding: utf-8 -*-
"""Pandas Chapter1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sKcVmtHpKAhEzfgI60FHRY9l8WKgMfY4

# Load Data
"""

import pandas as pd

# Replace 'path/to/your/csv' with the authentic file pathway on your local apparatus

file_path = '/content/titanic.csv'

data = pd.read_csv(file_path)

"""# Examine the Data"""

# Display the initial few records within the DataFrame
print(data.head())

# Disclose the dimensions (number of rows and columns) of the DataFrame
print(data.shape)

# Unveil the data types attributed to each column in the DataFrame
print(data.dtypes)

# Present a concise summary encompassing statistical metrics pertinent to numerical columns
print(data.describe())

"""# Select Specific Columns"""

# Isolate the 'Name' column
name = data['Name']

# Extract multiple columns, such as 'Sex' and 'Age'
selected_columns = data[['Sex', 'Age']]

"""# Select Specific Rows Through Slicing"""

# Capture the first ten rows within the DataFrame
first_10_rows = data[:10]

"""# Select Rows Based on Conditions"""

# Identify rows wherein 'Survived' is equivalent to 1 (representing Survived customers)
survived_people = data[data['Survived'] == 1]

"""# Modify Data Values"""

# Enhance the values within the 'Fare' column by incrementing each value by 10 units
data['Fare'] = data['Fare'] + 10

"""# Add a new column"""

# Add a new column 'Fare_Categories' based on the
def fare_category(fare):
    if fare < 10:
        return 'Very Low'
    elif fare < 30:
        return 'Low'
    elif fare < 60:
        return 'Moderate'
    elif fare < 100:
        return 'High'
    else:
        return 'Very High'

# Apply the fare_category function to create the new column
data['Fare_Categories'] = data['Fare'].apply(fare_category)

"""# Drop a column"""

# Drop the 'Ticket' column
data = data.drop('Ticket', axis=1)

"""# Save the modified DataFrame to a new CSV file"""

# Save the modified DataFrame to a new CSV file
data.to_csv('Modified_titanic.csv', index=False)

